service: lambda-layers-gem

custom:
  myStage: ${opt:stage, self:provider.stage}
  myProfile:
    prod: prodAccount
    dev: devAccount
    stage: stageAccount

provider:
  name: aws
  runtime: ruby2.5
  stage: dev
  region: us-east-1
  profile: ${self:custom.myProfile.${self:custom.myStage}}

layers:
  gemPacks:
    path: layer
    description: A Layer with common ruby gems.
    compatibleRuntimes:
      - ruby2.5